Document: xenedu-hpraid
Title: Debian xenedu-hpraid Manual
Author: <insert document author here>
Abstract: This manual describes what xenedu-hpraid is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xenedu-hpraid/xenedu-hpraid.sgml.gz

Format: postscript
Files: /usr/share/doc/xenedu-hpraid/xenedu-hpraid.ps.gz

Format: text
Files: /usr/share/doc/xenedu-hpraid/xenedu-hpraid.text.gz

Format: HTML
Index: /usr/share/doc/xenedu-hpraid/html/index.html
Files: /usr/share/doc/xenedu-hpraid/html/*.html
