Document: xenedu-lindomus
Title: Debian xenedu-lindomus Manual
Author: <insert document author here>
Abstract: This manual describes what xenedu-lindomus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xenedu-lindomus/xenedu-lindomus.sgml.gz

Format: postscript
Files: /usr/share/doc/xenedu-lindomus/xenedu-lindomus.ps.gz

Format: text
Files: /usr/share/doc/xenedu-lindomus/xenedu-lindomus.text.gz

Format: HTML
Index: /usr/share/doc/xenedu-lindomus/html/index.html
Files: /usr/share/doc/xenedu-lindomus/html/*.html
