Document: xenedu-base
Title: Debian xenedu-base Manual
Author: <insert document author here>
Abstract: This manual describes what xenedu-base is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xenedu-base/xenedu-base.sgml.gz

Format: postscript
Files: /usr/share/doc/xenedu-base/xenedu-base.ps.gz

Format: text
Files: /usr/share/doc/xenedu-base/xenedu-base.text.gz

Format: HTML
Index: /usr/share/doc/xenedu-base/html/index.html
Files: /usr/share/doc/xenedu-base/html/*.html
