#!/bin/bash
#
# script de migration LCS pour XenEdu
# Simon Cavey 01/06/2010
#
source /etc/xenedu/xenedu.conf
source /usr/sbin/xenedu-migre-linux-common

check-espace-disque lcs

echo -n "Entrez l'adresse IP du LCS reference : "
read serveurip
export $serveurip

installkey
#installkeyrev

# creation des partitions
lvcreate -L5G -n xenedu-lcs-root $XENEDUDISK
lvcreate -L10G -n xenedu-lcs-var $XENEDUDISK
lvcreate -L10G -n xenedu-lcs-varlog $XENEDUDISK
lvcreate -L10G -n xenedu-lcs-varspoolsquid $XENEDUDISK
lvcreate -L10G -n xenedu-lcs-usrsharelcs $XENEDUDISK
lvcreate -L10G -n xenedu-lcs-www $XENEDUDISK
lvcreate -L512M -n xenedu-lcs-swp $XENEDUDISK

# Question sur /home
oldhomeseize=`ssh -q root@$serveurip "df -h /home" |grep home | awk {'print $2'}`
oldhomeoqp=`ssh -q root@$serveurip "df -h /home" |grep home | awk {'print $5'}`
oldhomepc=`ssh -q root@$serveurip "df -h /home" |grep home | awk {'print $3'}`

clear
xenedu-freespace
echo "Sur votre LCS la partition /home fait $oldhomeseize"
echo "elle est utilisée à $oldhomesepc p t$oldhomeoqp"
echo "quelle taille souhaitez-vous pour la partion /home du nouveau lcs"
echo "indiquez l'espace pour /home les donnees utilisateurs"
echo "entrez simplement le nombre de Go souhaite"
read LCSHOMESIZE
lvcreate -L"$LCSHOMESIZE"G -n xenedu-lcs-home $XENEDUDISK

# formatage des partitions : 
for i in  $XENEDUDISK/xenedu-lcs-*; do
clear
echo "##### FORMATAGE DES PARTITIONS DU NOUVEAU LCS #####" 
mkfs.ext3 -m4 $i
done

mkdir -p /mnt/xenedutmp/migrelcs

mount $XENEDUDISK/xenedu-lcs-root /mnt/xenedutmp/migrelcs
mkdir -p /mnt/xenedutmp/migrelcs/var
mount $XENEDUDISK/xenedu-lcs-var /mnt/xenedutmp/migrelcs/var
mkdir -p /mnt/xenedutmp/migrelcs/var/log
mkdir -p /mnt/xenedutmp/migrelcs/var/www
mkdir -p /mnt/xenedutmp/migrelcs/home
mkdir -p /mnt/xenedutmp/migrelcs/usr/share/lcs
mkdir -p /mnt/xenedutmp/migrelcs/var/spool/squid
mount $XENEDUDISK/xenedu-lcs-varlog /mnt/xenedutmp/migrelcs/var/log
mount $XENEDUDISK/xenedu-lcs-www /mnt/xenedutmp/migrelcs/var/www
mount $XENEDUDISK/xenedu-lcs-varspoolsquid /mnt/xenedutmp/migrelcs/var/spool/squid
mount $XENEDUDISK/xenedu-lcs-usrsharelcs /mnt/xenedutmp/migrelcs/usr/share/lcs
mount $XENEDUDISK/xenedu-lcs-home /mnt/xenedutmp/migrelcs/home

# copie des données : 
clear
echo "copie des donnees"
ssh -q root@$serveurip "tar  --one-file-system -cf - /" |tar xf - -C /mnt/xenedutmp/migrelcs
ssh -q root@$serveurip "tar  --one-file-system -cf - /var" |tar xf - -C /mnt/xenedutmp/migrelcs
ssh -q root@$serveurip "tar  --one-file-system -cf - /var/log" |tar xf - -C /mnt/xenedutmp/migrelcs
ssh -q root@$serveurip "tar  --one-file-system -cf - /usr/share/lcs" |tar xf - -C /mnt/xenedutmp/migrelcs
ssh -q root@$serveurip "tar  --one-file-system -cf - /home" |tar xf - -C /mnt/xenedutmp/migrelcs

# correction des droits squid : 
proxyuid=cat /mnt/xenedutmp/migrelcs/etc/passwd | grep "^proxy:" | cut -f 3 -d ":"
proxygid=cat /mnt/xenedutmp/migrelcs/etc/passwd | grep "^proxy:" | cut -f 4 -d ":"
chown $proxyuid:$proxygid /mnt/xenedutmp/migrelcs/var/spool/squid

# Remplacement des modules
rm -rf /mnt/xenedutmp/migrelcs/lib/modules/*
cp -a /lib/modules/*xen* /mnt/xenedutmp/migrelcs/lib/modules

# Supression de config reseau udev
rm -rf /mnt/xenedutmp/migrelcs/etc/udev/rules.d/*-net*

# ecriture du nouveau Fstab

cat > /mnt/xenedutmp/migrelcs/etc/fstab <<E_O_TAB
/dev/sda1       /               ext3    defaults,errors=remount-ro 0       1
/dev/sda2       none            swap    sw              0       0
/dev/sda10      /home           ext3    defaults        0       2
/dev/sda6       /usr/share/lcs  ext3    defaults        0       2
/dev/sda7       /var            ext3    defaults        0       2
/dev/sda8       /var/log        ext3    defaults        0       2
/dev/sda9       /var/spool/squid ext3    defaults        0       2
/dev/sda11      /var/www          ext3    defaults        0       2
proc          /proc    proc     defaults              0     0
E_O_TAB


# ecriture du fichier de config xen
cat > /etc/xen/xenedu-lcs.cfg <<E_O_XEN
kernel = "/boot/vmlinuz-2.6.26-2-xen-amd64"
ramdisk = "/boot/initrd.img-2.6.26-2-xen-amd64"
memory = 1024
name   = "xenedu-lcs"
vif = [ 'bridge=eth0' ]
disk   = [ 'phy:$XENEDUDISK/xenedu-lcs-root,sda1,w',
'phy:$XENEDUDISK/xenedu-lcs-swp,sda2,w',
'phy:$XENEDUDISK/xenedu-lcs-home,sda10,w',
'phy:$XENEDUDISK/xenedu-lcs-usrsharelcs,sda6,w',
'phy:$XENEDUDISK/xenedu-lcs-var,sda7,w',
'phy:$XENEDUDISK/xenedu-lcs-varlog,sda8,w',
'phy:$XENEDUDISK/xenedu-lcs-varspoolsquid,sda9,w'
'phy:$XENEDUDISK/xenedu-lcs-www,sda11,w', ]
root   = "/dev/sda1 ro"
extra = "4 xencons=tty"
#dhcp="dhcp"

E_O_XEN

# Ajout du lcs au boot du dom0
cd /etc/xen/auto
ln -snf ../xenedu-lcs.cfg 01-xenedu-lcs.cfg

# Arret du LCS physque et demarrage du lcs virtuel
echo "Faut-il arreter le LCS physique et demarrer le virtuel maintenant : (o/N)"
read reponse
if [ $reponse="o" ]; then
	echo "arret du LCS"
	ssh root@$serveurip "halt"
	echo "attente de 10 seconde avant demarrage LCS"
	sleep 10
	xm create xenedu-lcs.cfg
else
	echo "vous pouvez eteindre le LCS physique"
	echo "tapez "
	echo "     xm create xenedu-lcs.cfg "
	echo "pour demarrer le LCS virtuel"
fi
                        
