#!/bin/bash

# On test les volumes logiques :

for vl in `echo "ctrl all show config"  | hpacucli | grep "logicaldrive" | awk  {'print  $2 '}`
do
	vlcheck=`echo "ctrl all show config"  | hpacucli | grep "logicaldrive $vl" | awk  {'print  $7 '}`

	if [ "$vlcheck" == "OK)" ] && [ "$1" != "-v" ] ; then
		echo "le volume logique $vl est correct ($vlcheck"
 	elif [ "$vlcheck" == "Recovering," ] ; then
                 echo "Le volume $vl est en reconstruction"
	else
		echo "le volume logique $vl est $vlcheck"
		echo -e "Détail des disques : "
		for disk in `echo "ctrl all show config"  | hpacucli | grep "physicaldrive" | awk  {'print  $2 '}`
		do
			diskcheck=`echo "ctrl all show config"  | hpacucli | grep "physicaldrive $disk" | awk  {'print  $10 '}`
			if [ "$diskcheck" == "OK)" ] ; then
	                	echo -e "\t Le disque $disk est OK"
                        elif [ "$diskcheck" == "Rebuilding)" ] ; then
                        	echo -e"\t Le disque $disk du volume logique $vl est en reconstruction"
			elif [ "$diskcheck" == "Failed)" ] ; then
			        echo -e "\t Le disque $disk est en erreur Failed"
			fi
		done
	fi
done

