#!/bin/bash
# creation d'une VM SE3 squeeze
# XenEdu - Simon Cavey - 03/06/2015

source /etc/xenedu/xenedu.conf

xenedu-freespace

echo "indiquez l'espace pour /home les donnees utilisateurs"
echo "entrez simplement le nombre de Go souhaite"
read SE3HOMESIZE

xenedu-freespace
echo "indiquez l'espace pour /var/se3 les donnees communes"
echo "entrez simplement le nombre de Go souhaite"
read SE3VARSE3SIZE

DOMAINE=`hostname -d`

echo "indiquez le masque de sous-reseau pour le SE3 :"
read NETMASK0

echo "indiquez l'ip pour le SE3 :"
read SE3IP

GATEWAY=`route -n | grep ^0.0.0.0 | awk '{print $2}'`

echo "indiquez le nombre de CPU a allouer"
read VCPUNUM


echo "indiquez en Mo la memoire a allouer au SE3 :"
read SE3MEMORY

cp /etc/xen-tools/partitions.d/xenedu-se3.in  /etc/xen-tools/partitions.d/xenedu-se3

sed -i'' 's/@@HOMESE3SIZE@@/$SE3HOMESIZE/g'  /etc/xen-tools/partitions.d/xenedu-se3
sed -i'' 's/@@VARSE3SIZE@@/SE3VARSE3SIZE/g'  /etc/xen-tools/partitions.d/xenedu-se3

 
xen-create-image --config=/etc/xen-tools/xenedu-se3.conf  --hostname=se3pdc.$DOMAIN --role=se3 --partitions=xenedu-se3 --force --ip=$SE3IP --gateway=$GATEWAY  --netmask=$NETMASK0 --vcpus=$VCPUNUM −−memory=$SE3MEMORY  --bridge=xenbreth0
