#!/bin/bash
source /etc/xenedu/xenedu.conf

DISKSIZE=`vgdisplay $XENEDUDISK | grep "VG Size"| awk {'print $3'} | cut -d, -f1`
DISKFREE=`vgdisplay $XENEDUDISK | grep Free| awk {'print $7 '} | cut -d, -f1`
FREERATIO=`echo $(($DOTDISKFREE*100/$DOTDISKSIZE))`

echo "Vous disposez de $DISKFREE Go d'espace disque pour les machines virtuel soit $FREERATIO % de l'espace de stockage"
