#!/bin/bash
#
# Preparation de la config Windows 7
# XenEdu - Simon Cavey - simon.cavey@crdp.ac-caen.fr
# 12/01/2011
#

source /etc/xenedu/xenedu.conf
# Generation de l'adresse Mac
$XENMAC=`xenedu-mac-generator`


cp /var/lib/xenedu/base/windows-7-xen-modoel /etc/xen/win7.cfg
sed -i'' 's/@@XENMAC@@/$XENMAC/g' /etc/xen/win7.cfg

