Document: xenedu-windomus
Title: Debian xenedu-windomus Manual
Author: <insert document author here>
Abstract: This manual describes what xenedu-windomus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xenedu-windomus/xenedu-windomus.sgml.gz

Format: postscript
Files: /usr/share/doc/xenedu-windomus/xenedu-windomus.ps.gz

Format: text
Files: /usr/share/doc/xenedu-windomus/xenedu-windomus.text.gz

Format: HTML
Index: /usr/share/doc/xenedu-windomus/html/index.html
Files: /usr/share/doc/xenedu-windomus/html/*.html
