Document: xenedu-netbsdomus
Title: Debian xenedu-netbsdomus Manual
Author: <insert document author here>
Abstract: This manual describes what xenedu-netbsdomus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xenedu-netbsdomus/xenedu-netbsdomus.sgml.gz

Format: postscript
Files: /usr/share/doc/xenedu-netbsdomus/xenedu-netbsdomus.ps.gz

Format: text
Files: /usr/share/doc/xenedu-netbsdomus/xenedu-netbsdomus.text.gz

Format: HTML
Index: /usr/share/doc/xenedu-netbsdomus/html/index.html
Files: /usr/share/doc/xenedu-netbsdomus/html/*.html


