#!/bin/bash
#
# Script pour inverser Eth0 et Eth1 sur le serveur physique.
# Projet XenEdu - Simon Cavey - 31/01/2011
#

echo "Inversion de eth0 et de eth1"

sed -i'' -e 's/eth0/ethTEMP/g' -e 's/eth1/eth0/g' -e 's/ethTEMP/eth1/g' /etc/udev/rules.d/70-persistent-net.rules

echo "Les cartes eth0 et eth1 sont inversees"
echo "Le changement sera applique au prochain demarrage du serveur physique (dom0)"
echo "Pour annuler relancer le script xenedu-change-eth"
