#!/bin/bash
# XenEduMaj
# script de mise a jour de XenEdu basé sur LcsMaj
# Simon Cavey - simon.cavey@crdp.ac-caen.fr
# 15/06/2010
####



PATH="/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/share/lcs/sbin:/usr/share/lcs/scripts"
export DEBIAN_PRIORITY="critical"
export DEBIAN_FRONTEND="noninteractive"
WGETOPTIONS="-nv -o wget.log -T 5 -t 2"

### Mise a jour des paquets debian
apt-get update
apt-get -y --force-yes upgrade

### Récuperation des variable de mise a jour : 
#URLMAJTGZ=`cat /etc/xenedu/update | grep "URLMAJTGZ" |cut -d "=" -f 2`
#URLMAJMD5=`cat /etc/xenedu/update | grep "URLMAJMD5" |cut -d "=" -f 2`
MAJNBR==`cat /etc/xenedu/release | grep "MAJNBR" |cut -d "=" -f 2`
source /etc/xenedu/update

cd /root/XenEduMaj
#
# DL des fichiers md5
#
wget $URLMAJMD5/maj*.md5 $WGETOPTIONS -N
echo "Indice de maj actuelle : $MAJNBR"

#
# Application des scripts de maj
#

NEXT_MINOR_MAJ=$(( $MAJNBR+1 ))
NEXT_MAJOR_MAJ=$(( (($MAJNBR /10) * 10) + 10 ))

while [ -e maj$NEXT_MINOR_MAJ.md5  ] || [ -e maj$NEXT_MAJOR_MAJ.md5 ]; do

  if [ -e maj$NEXT_MINOR_MAJ.md5 ]
  then
    MAJNBR=$NEXT_MINOR_MAJ
  elif [ -e maj$NEXT_MAJOR_MAJ.md5 ]
  then
    MAJNBR=$NEXT_MAJOR_MAJ
  fi
    
  #echo "###DBG###<A0>application de maj$MAJNBR.sh"
  #
  # DL des fichiers d'archives
  #
  wget $URLMAJTGZ/maj$MAJNBR.tgz $WGETOPTIONS
  # Si le serveur ne repond pas -> exit
  if [ `grep -c maj wget.log` == 0 ]; then
      echo "Serveur des archives de mise a jour indisponible !"
      rm wget.log
      exit 1 
  fi
  #
  # On s'assure que l'archive de maj existe
  #
  if [ -e maj$MAJNBR.tgz ]; then
    #
    # Verification de la validite du telechargement
    #
    RESULT=`/usr/bin/md5sum maj$MAJNBR.tgz`
    RESULT1=`cat maj$MAJNBR.md5`
    if [ "$RESULT" = "$RESULT1" ]; then
      tar zxf maj$MAJNBR.tgz
      #
      # Application du script de maj
      #
      echo "Application de la mise a jour N<B0> $MAJNBR"
      ./maj$MAJNBR.sh
      #
      # Update de l'indice de maj du LCS
      #      
      echo "UPDATE params SET value='$MAJNBR' WHERE name='majnbr'"| $MYSQLCNX      
      rm *.tgz maj*.sh wget.log
    else
      # Si validite du telechargement non conforme -> exit
      echo "L'archive de mise a jour N<B0> $MAJNBR n'est pas conforme, operation annulee !" 
      rm maj*.tgz wget.log
      exit 1
    fi
  else
    echo "Le telechargement de l'archive de mise a jour N<B0> $MAJNBR a echouee, op<E9>ration annulee !"
    exit 1
  fi
  
  NEXT_MINOR_MAJ=$(( $MAJNBR+1 ))
  NEXT_MAJOR_MAJ=$(( (($MAJNBR /10) * 10) + 10 ))
done

echo "Toutes les revisions ou mises a jour disponibles ont ete appliquees."
export DEBIAN_PRIORITY="high"
export DEBIAN_FRONTEND="dialog"
