#!/bin/bash
#
# Script d'installation auto lcs
# Simon Cavey
# Release XenEdu Jessie by jLCF <jean-luc.chretien@ac-caen.fr>
# 13/10/2017


source /etc/xenedu/xenedu.conf

xenedu-freespace
echo "indiquez l'espace pour /home les donnees utilisateurs"
echo "entrez simplement le nombre de Go souhaite"
read LCSHOMESIZE


xenedu-freespace
echo "indiquez l'espace pour /var/spool/squid le cache Web"
echo "entrez simplement le nombre de Go souhaite "
read LCSVARSQUID

sed -e "s|@@HOMESIZE@@|$LCSHOMESIZE|g" \
-e "s|@@CACHESIZE@@|"$LCSVARSQUID"|g" \
/etc/xen-tools/partitions.d/lcs-custom.in > /etc/xen-tools/partitions.d/lcs-custom

echo "indiquez votre n° de preseed"
read PRESEEDNUM

echo "indiquer le nombre de CPU a allouer"
read VCPUNUM

mkdir -p /etc/xen-tools/skel/lcs/root
mkdir -p /etc/xen-tools/skel/lcs/etc/lcs

wget "http://dimaker.tice.ac-caen.fr/diconf/$PRESEEDNUM/lcs.preseed"  -O /etc/xen-tools/skel/lcs/root/lcs.preseed
wget "http://dimaker.tice.ac-caen.fr/diconf/$PRESEEDNUM/lcs.conf" -O /etc/xen-tools/skel/lcs/etc/lcs/lcs.conf
sed -i'' '/^d-i /d' /etc/xen-tools/skel/lcs/root/lcs.preseed
MOTDEPASSEALEATOIR=`pwgen 10 1`
sed -i'' "s/AUTO/string $MOTDEPASSEALEATOIR/g"  /etc/xen-tools/skel/lcs/root/lcs.preseed
sed -i'' "s/AUTO/$MOTDEPASSEALEATOIR/g"  /etc/xen-tools/skel/lcs/etc/lcs/lcs.conf
MYSQLPASS=`pwgen 10 1`
sed -i'' "s/MYSQLPW=$MOTDEPASSEALEATOIR/MYSQLPW=$MYSQLPASS/g"  /etc/xen-tools/skel/lcs/etc/lcs/lcs.conf
echo "mysql-server mysql-server/root_password select $MYSQLPASS" >> /etc/xen-tools/skel/lcs/root/lcs.preseed
echo "mysql-server mysql-server/root_password_again select $MYSQLPASS" >> /etc/xen-tools/skel/lcs/root/lcs.pres$
echo "[client]" > /etc/xen-tools/skel/lcs/root/.my.cnf-not-set
echo "                password=$MYSQLPASS" >> /etc/xen-tools/skel/lcs/root/.my.cnf-not-set
echo "                user=root" >> /etc/xen-tools/skel/lcs/root/.my.cnf-not-set

source /etc/xen-tools/skel/lcs/etc/lcs/lcs.conf

xen-create-image --config=/etc/xen-tools/xenedu-lcs.conf \
	--hostname=lcs.$DOMAIN \
	--role=lcs \
	--partitions=lcs-custom \
	--force --ip=$IPADDR0 \
	--gateway=$GATEWAY \
	--netmask=$NETMASK0 \
	--vcpus=$VCPUNUM \
	--lvm=$XENEDUVOL \
	--bridge=xenbreth0 \
	--dist=jessie

mv /etc/xen/lcs.$DOMAIN.cfg  /etc/xen/xenedu-lcs.cfg
#ln -snf /etc/xen/xenedu-lcs.cfg /etc/xen/auto/01-xenedu-lcs.cfg
echo "pour lancer le LCS taper la commande : "
echo "xl create /etc/xen/xenedu-lcs.cfg -c"
