#!/bin/bash
# configure the new image to be a minimal image, by removing
# packages I don't care about - and installing new ones I prefer.
#
# Steve
# --
# http://www.steve.org.uk/
#


prefix=$1



#
#  Source our common functions - this will let us install a Debian package.
#
if [ -e /usr/share/xen-tools/common.sh ]; then
    . /usr/share/xen-tools/common.sh
else
    echo "Installation problem"
fi

#
#  Install some new packages - do this first to avoid dependency errors.
#
#installDebianPackage ${prefix} syslog-ng 
installDebianPackage ${prefix} deborphan
installDebianPackage ${prefix} less
installDebianPackage ${prefix} screen
installDebianPackage ${prefix} sudo
installDebianPackage ${prefix} vim
installDebianPackage ${prefix} udev
#installDebianPackage ${prefix} openssh-server
installDebianPackage ${prefix} postfix
installDebianPackage ${prefix} mailx
installDebianPackage ${prefix} ntp
installDebianPackage ${prefix} bzip2
#installDebianPackage ${prefix} yafc
installDebianPackage ${prefix} tree

#
#  Remove some standard packages.
#

# PPP stuff.
removeDebianPackage ${prefix} pppconfig
removeDebianPackage ${prefix} pppoeconf
removeDebianPackage ${prefix} pppoe
removeDebianPackage ${prefix} ppp
removeDebianPackage ${prefix} libpcap0.7

# Editors
#removeDebianPackage ${prefix} nano
#removeDebianPackage ${prefix} ed
#removeDebianPackage ${prefix} nvi

# Sys
#removeDebianPackage ${prefix} klogd
#removeDebianPackage ${prefix} sysklogd

# manpages
removeDebianPackage ${prefix} manpages  
removeDebianPackage ${prefix} man-db 
removeDebianPackage ${prefix} info

# misc
#removeDebianPackage ${prefix} tasksel tasksel-data
#removeDebianPackage ${prefix} pciutils
#removeDebianPackage ${prefix} fdutils
#removeDebianPackage ${prefix} cpio
#
# Ajout du dépot lcs
#
echo "deb http://lcs.crdp.ac-caen.fr/jessie LcsXP main" >> ${prefix}/etc/apt/sources.list
echo "APT::Get::AllowUnauthenticated 1;" >> ${prefix}/etc/apt/apt.conf.d/00install-lcs

#
# Upgrade packages
#
chroot ${prefix} /usr/bin/apt-get update
chroot ${prefix} /usr/bin/apt-get upgrade -y
chroot ${prefix} /usr/bin/apt-get clean
#
# Copy skel
#
cp -a /etc/xen-tools/skel/lcs/* ${prefix}

#
# Copie des modules :
#
#cp -a /lib/modules/`uname -r` ${prefix}/lib/modules
#chroot ${prefix}  /sbin/depmod -a
#
#
chroot ${prefix} debconf-set-selections < /root/lcs/lcs.preseed

#
# Modif de /etc/hosts
#
/bin/sed -i 's/minimal/'${hostname}'/g' ${prefix}/etc/hosts

# 
# Ajout de paquets LCS
#
installDebianPackage ${prefix} debian-lcs-keyring lcs-preinstall lcs-dns lcs-web lcs-smtp lcs-imap lcs-roundcube lcs-sysinfo lcs-security
