#!/bin/bash
# Xenedu Wheezy to Jessie
# xenedu-upgrade-jessie 
# 07/12/2017 jLCF jean-luc.chretien@ac-caen.fr
# ---------------------------------------------------------------------------
# Phase 0 : Preparatoire
# Phase 1 : On vire les xeneries et on passe sur un noyau squeeze 3.2 non Xen Upgrade Jessie Installation XenEdu
# Phase 2 : Finalisation
# ---------------------------------------------------------------------------

#Couleurs

COLTITRE="\033[1;35m"          # Rose
COLCMD="\033[1;37m"            # Blanc
COLQUESTION="\033[1;32m"       # Vert
COLPARTIE="\033[1;34m"         # Bleu
COLERR="\033[1;31m"  	       # Rouge
COLTXT="\033[0;37m"            # Gris
COLINFO="\033[0;36m"	       # Cyan

# Fonctions 
go()
{
# On demande confirmation
echo -e "$COLQUESTION"
echo "Faut-il lancer la phase : $1 ? (o/N) "
echo -e "$COLCMD"
read STARTUPGRADE
if [ $STARTUPGRADE != "o" ]; then
	echo -e "$COLERR"
	echo "Mise a jour annulee !"
	echo -e "$COLCMD"
	exit 1
else
	echo -e "$COLINFO"
	echo "Lancement de la mise a jour..."
	echo -e "$COLCMD"
fi
}

verif()
{
# On demande confirmation
echo -e "$COLQUESTION"
echo "Cette configuration vous semble bonne ? (o/N)"
echo -e "$COLCMD"
read VISU
if [ $VISU != "o" ]; then
	echo -e "$COLERR"
	echo "ERR : Interruption de la phase de mise a jour"
	echo -e "$COLCMD"	
	exit 1
else
	echo -e "$COLINFO"
	echo "On continue..."
	echo -e "$COLCMD"	
fi
}

wait()
{
echo -e "$COLINFO"
echo "tapez une touche pour continuer"
echo -e "$COLCMD"
read WAIT
}

netconfig()
{
cp /etc/network/interfaces /root/interfaces.xenedu.wheezy	
IFIP=`ifconfig | grep  "inet adr" | grep -v 127 | cut -f 2 -d ":" | cut -f 1 -d " "`
IFMASK=`ifconfig | grep  "inet adr" | grep -v 127 | cut -f 4 -d ":"`
IFBCAST=`ifconfig | grep "inet adr:" | grep -v 127 | cut -f 3 -d ":" | cut -f 1 -d " "`
IFNET=`ipcalc -n  $IFIP $IFMASK | grep "Network" | awk '{print $2}'| cut -f 1 -d "/"`
IFGATE=`route -n | grep eth0 | grep "^0.0.0.0"| awk '{print $2}'`

echo "auto lo
iface lo inet loopback

allow-hotplug eth0
iface eth0 inet static
    address $IFIP
    network $IFNET
    netmask $IFMASK
    broadcast $IFBCAST
    gateway $IFGATE" > /etc/network/interfaces
}

# Si at n'est pas la, on l'installe
if [ ! -f /usr/bin/at ]; then
	apt-get install at -y
fi


if [ ! -f /root/phasemigrexenedu ]; then
# Phase 0
#--------
	# On test la version Debian
	DEBVERSION=`cat /etc/debian_version |cut -f 1 -d .`
	if [ "$DEBVERSION" != "7" ]; then
		echo -e "$COLERR"
		echo "Err: ce script est prevu pour Debian Wheezy uniquement."
		echo -e "$COLCMD"
      exit 1
	fi
	# On install grub-pc, si celui ci n'est pas installé
	if [ ! -f /etc/default/grub ];then
        echo "install grub-pc" -y
	fi
	# On test si il existe un acces ssh rgateway
	if [ `ps aux | grep StrictHostKeyChecking | wc -l` != "2" ]; then
		echo -e "$COLINFO"
    	echo "Vous DEVEZ acceder au Dom0 depuis une session ssh secours"
    	echo "Lancez xenedu-secours-ssh puis vous connecter via rgateway et relancer le script"
		echo -e "$COLCMD"
    	exit 1
	fi
	# On demande confirmation pour le lancement de la Phase 0
	go 0
	# On conserve les scripts ssh secours, la conf xen, le dossier rssh...
	echo -e "$COLINFO"	
	echo "Migration Wheezy Jessie XenEdu : Phase 0"
	echo -e "$COLCMD"
	mkdir -p /root/secours
	cp /sbin/xenedu-secours-ssh /root/secours/
	cp /sbin/xenedu-stop-secourssh /root/secours/
	cp /sbin/xenedu-get-TiceKey /root/secours/
	cp -a /etc/xen /root/secours/xenconf
	cp -a /home/rssh /root/secours/
	# On shut les vm pour continuer a travailler depuis rgateway
	echo -e "$COLINFO"	
	echo "Arret des DomU :"
	echo -e "$COLCMD"	
	for vm in `xm list 2>>/dev/null | cut -f 1 -d " "|grep -v "Name"| grep -v "Domain-0"`
	do
		echo "Arret de $vm"
    	xm shut $vm 2>>/dev/null
    	sleep 60
    	xm dest $vm 2>>/dev/null
	done
	# On sauvegarde le xen auto
	mkdir -p /root/xenautosav
	mv /etc/xen/auto/* /root/xenautosav/
	# Reconfiguration network standard
	netconfig eth0
	# Desintallation de XenEdu et Xen
	echo -e "$COLINFO"	
	echo "Migration Wheezy Jessie XenEdu : Desintallation de XenEdu et Xen"
	echo -e "$COLCMD"
	# On vire les xeneries
	apt-get remove xenstore-utils -y
	apt-get remove xenedu-lindomus -y
	apt-get remove xenedu-base -y
	apt-get remove xen-tools -y
	apt-get remove xen-hypervisor-4.1-amd64 -y
	# On remet en place les elements pour le ssh secours
	cp -a /root/secours/rssh /home/
	cp /root/secours/xenedu-* /sbin/
	chown -R rssh:rssh /home/rssh
	chmod 755 /home/rssh
	chmod -R 700 /home/rssh/.ssh
	#
	# Modif source list
	echo -e "$COLINFO"		
	echo "Changement des sources en wheezy"
	echo -e "$COLCMD"		
	cat > /etc/apt/sources.list <<EOF
deb http://ftp.fr.debian.org/debian/ jessie main non-free contrib
deb-src http://ftp.fr.debian.org/debian/ jessie main non-free contrib

deb http://security.debian.org/ jessie/updates main contrib non-free
deb-src http://security.debian.org/ jessie/updates main contrib non-free

## XenEdu
deb http://xenedu.crdp.ac-caen.fr/jessie xeneduXP main
EOF

	echo -e "$COLINFO"		
	echo "Migration Wheezy Jessie XenEdu : Phase 0"
	echo "Mise a jour de la distribution en Jessie"
	echo -e "$COLCMD"	
	apt-get update
	apt-get install debian-archive-keyring
	apt-get -y --force-yes dist-upgrade	
	
	# On se prepare a ouvrir apres reboot un session ssh de secours automatiquement
	PORTMIN=10000
	PORTMAX=20000
	nombre=0   #initialise
	while [ "$nombre" -le $PORTMIN ]
	do
  		nombre=$RANDOM
 		let "nombre %= $PORTMAX"  # Ramene $nombre dans $ECHELLE.
	done
	# Preparation demarrage d'un session ssh-secours au reboot
	echo -e "$COLINFO"		
	echo "Au prochain reboot le numero de port pour le ssh secours sera $nombre"
	echo -e "$COLCMD"	

	echo "#!/bin/sh" > /etc/init.d/sshsecours
	echo "### BEGIN INIT INFO" >> /etc/init.d/sshsecours
	echo "# Provides:        sshsecours" >> /etc/init.d/sshsecours
	echo "# Required-Start:    $remote_fs $syslog" >> /etc/init.d/sshsecours
	echo "# Required-Stop:    $remote_fs $syslog" >> /etc/init.d/sshsecours
	echo "# Default-Start:    2 3 4 5" >> /etc/init.d/sshsecours
	echo "# Default-Stop:0 1 6" >> /etc/init.d/sshsecours
	echo "# Short-Description: ssh secours rgateway" >> /etc/init.d/sshsecours
	echo "### END INIT INFO" >> /etc/init.d/sshsecours	
	echo "su -c \"/usr/bin/ssh -f -N -o 'StrictHostKeyChecking=no' -p22 -R $nombre:127.0.0.1:22 rssh@rgateway.crdp.ac-caen.fr\" rssh" >> /etc/init.d/sshsecours
	echo "exit 0" >> /etc/init.d/sshsecours
	chmod +x /etc/init.d/sshsecours
	update-rc.d sshsecours defaults	
	echo "1" > /root/phasemigrexenedu
	# 1er reboot
	# On reboot sur le noyau 3.16.0-4 pas xen
	echo -e "$COLINFO"	
	echo "Fin phase 1, on reboot..."
	echo -e "$COLCMD"		
	wait
	reboot
	exit 0
	# Fin Phase 0
fi

# Phase 1
# -------
if grep "1" /root/phasemigrexenedu; then
	# On demande confirmation
	go 1
	echo -e "$COLINFO"
	echo "Migration Wheezy Jessie XenEdu : Phase 1"
	echo "Installation des Xeneries Jessie..."
	echo -e "$COLCMD"
	# On efface les /sbin/xenedu*
	rm -f /sbin/xenedu*
	# On installe les nouvelles Xeneries
	apt-get install xenedu-base -y
	apt-get install xenedu-lindomus -y
	# reconfiguration network a la mode Xen
	xenedu-network-reconfig eth0
	# Quatrieme reboot
	echo -e "$COLINFO"
	echo "Fin phase 3, on reboot..."
	echo "Vous pourrez relancer le script en reouvrant une session ssh de secours"
	echo "avec le meme numero que precedement..."
	echo -e "$COLCMD"
	echo "2" > /root/phasemigrexenedu
	wait
	reboot
	exit 0
fi

# Phase 2
#---------
if grep "2" /root/phasemigrexenedu; then
	# On demande confirmation
	go 2
	echo -e "$COLINFO"
	echo "Migration Wheezy Jessie XenEdu : Phase 2"
	echo "Finalisation et verifications"
	echo -e "$COLCMD"
	# On verifie que le xend est up
	if ! xl list | grep "Domain-0"; then
		echo -e "$COLERR"
		echo "ERR : Pas de daemon xend up le daemon xend ne semble pas fonctionnel..."
        echo -e "$COLCMD"	
	else
		echo -e "$COLINFO"
		echo "Xend up :)"
		echo "Il faut desormais modifier les DomU manuellement..."
		echo -e "$COLCMD"
		# On efface la session ssh secours au reboot
		update-rc.d sshsecours remove
		rm -f /etc/init.d/sshsecours
	fi	           
fi

# FIN

