#!/bin/bash
################################################################
################# SCRIPT UPGRADE XEN EN WHEEZY #################
################################################################

##
## Confirmation Exécution du script
##

echo "Faut-il mette a jour maintenant ? (o/n)"
read rep

if [ "$rep" = "o" ];then
	lsb_release --all > /tmp/lsb_release
	xenedu-version > /tmp/xenedu_version
else
	echo "changement de la distribution annulé!"
	exit 1
fi

##
## Fichier de log
##

echo "_/!\_ Fichier de log disponible: /var/log/xen/upgrade.log _/!\_ "
echo "Voulez-vous enregistrer les sorties des commandes dans le fichier de log ? (o/n)"
read rep

if [ "$rep" = "o" ];then
	terminal="/var/log/xen/upgrade.log"
else
	terminal=`tty`
fi

##
## Parametrage du Gestionaire de Paquets
##

export DEBIAN_FRONTEND=noninteractive
export DEBIAN_PRIORITY="critical"

##
## Debut Mise à Niveau
##

echo "------------------------------------------------------------------" > $terminal
echo "----           MISE A JOUR DE LA VERSION ACTUELLE             ----" >> $terminal
echo "------------------------------------------------------------------" >> $terminal
echo "------------------------------------------------------------------" >> $terminal
echo "mise a jour en démarrer!"
echo "#apt-get -y update" >> $terminal
apt-get -y update >> $terminal
echo "apt-get update... [ok]"
echo "------------------------------------------------------------------" >> $terminal
echo "mise à niveau de la distribution"
echo "#apt-get -y upgrade" >> $terminal
apt-get -y upgrade >> $terminal
echo "apt-get upgrade... [ok]"

##
## Changement des Sources
##

echo "------------------------------------------------------------------" >> $terminal
echo "changement des sources en wheezy"
cat > /etc/apt/sources.list <<EOF
deb http://ftp.fr.debian.org/debian/ wheezy main non-free contrib
deb-src http://ftp.fr.debian.org/debian/ wheezy main non-free contrib

deb http://security.debian.org/ wheezy/updates main contrib non-free
deb-src http://security.debian.org/ wheezy/updates main contrib non-free

## XenEdu
deb http://xenedu.crdp.ac-caen.fr/wheezy xenedu main
EOF

##
## Mise à Niveau depuis les nouvelles sources
##

echo "édition source terminée!" >> $terminal
echo "------------------------------------------------------------------" >> $terminal
echo "mise à jour depuis les sources de la nouvelles distribution"
echo "#apt-get -y update" >> $terminal
apt-get -y update >> $terminal
echo "apt-get update... [ok]"
echo "------------------------------------------------------------------" >> $terminal
echo "mise à niveau depuis les sources de la nouvelles distribution"
echo "#apt-get -y upgrade" >> $terminal
apt-get -y --force-yes upgrade >> $terminal
echo "apt-get upgrade... [ok]"
echo "------------------------------------------------------------------" >> $terminal
echo "/!\ /!\ ..Passage en Wheezy.. /!\ /!\ "
echo "#aptitude -y dist-upgrade" >> $terminal
apt-get -y --force-yes dist-upgrade >> $terminal
echo "apt-get dist-upgrade... [ok]"
echo "------------------------------------------------------------------" >> $terminal
echo "------------------------------------------------------------------" >> $terminal
echo "------------------------------------------------------------------"
echo "Edition de la priorité de boot pour remettre Linux_xen avant Linux"
dpkg-divert --divert /etc/grub.d/08_linux_xen --rename /etc/grub.d/20_linux_xen >> $terminal
echo "Misa a jour du Grub"
update-grub >> $terminal

echo "Mise à jour niveau!"
echo "=================="
echo "Version d'origine:"
echo "------------------"
cat /tmp/lsb_release
echo "------------------"
cat /tmp/xenedu_version
echo "=================="
echo "Version actuelle:"
echo "------------------"
lsb_release --all
echo "------------------"
xenedu-version
echo "=================="

echo "Voulez-vous mettre a jour les domU ?(o/n)"
echo "/!\ ATTENTION le système redémarerra aprés la mise a jour des domU /!\ "
read rep
if [ "$rep" = "o" ];then
	./xenedu-upgrade-wheezy-4vms
else
	echo "Mise à Jour des DomU annulé"
fi
echo "Fin Du Script"

