Document: xenedu-nut
Title: Debian xenedu-nut Manual
Author: <insert document author here>
Abstract: This manual describes what xenedu-nut is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/xenedu-nut/xenedu-nut.sgml.gz

Format: postscript
Files: /usr/share/doc/xenedu-nut/xenedu-nut.ps.gz

Format: text
Files: /usr/share/doc/xenedu-nut/xenedu-nut.text.gz

Format: HTML
Index: /usr/share/doc/xenedu-nut/html/index.html
Files: /usr/share/doc/xenedu-nut/html/*.html


