#!/bin/bash
#
# Information sur les bridges
# Simon Cavey - 31/01/2011
# Jean-Luc Chretien 05/05/2017
#

for i in `xl list  |grep -v "Name" |grep -v 0| awk '{print $2}'`
do
	BRIDGE=`xl list -l $i | grep "(bridge" |awk {'print $2'}|cut -f 1 -d ")"`
	NAME=`xl list -l 1 | grep "(name" |awk {'print $2'}|cut -f 1 -d ")"`
	echo "la machine virtuelle $NAME est raccordee sur la carte $BRIDGE"
done
