#!/bin/bash
#
# Correction du nom de domaine sur XenEdu
#

cp /etc/hosts /etc/hosts.backupxenedu
hostname -f 2>/tmp/testreadomain
testreadomain=`cat /tmp/testreadomain`
if [ "$testreadomain" == "hostname: Unknown host" ]; then
	localdomain=`cat /etc/resolv.conf|grep search| awk {'print  $2 '}` 
	newlocalhostdef="127.0.0.1	XenEdu.$localdomain XenEdu localhost"
	sed -i'' '/^127.0.0.1/d' /etc/hosts
	sed -i'' "1i$newlocalhostdef" /etc/hosts
	echo "domain corrige"
fi
rm /tmp/testreadomain
