#!/bin/sh
# prerm script for xenedu-base
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    remove)
	if [ -e /etc/issue.noxenedu ] ; then 
	    mv /etc/issue.noxenedu /etc/issue
	    cp /etc/issue /etc/issue.net
	fi
	if [ -e /etc/xen/xend-config.sxp.noxenedu ] ; then 
	    mv /etc/xen/xend-config.sxp.noxenedu /etc/xen/xend-config.sxp
	fi

	if [ -e /etc/ssh/sshd_config.noxenedu ] ; then 
	    mv /etc/ssh/sshd_config.noxenedu /etc/ssh/sshd_config
	fi

	if [ -x /usr/sbin/invoke-rc.d ]; then
	    invoke-rc.d xend restart
	else
	    /etc/init.d/xend restart
	fi
	if [ -x /usr/sbin/invoke-rc.d ]; then
	    invoke-rc.d ssh restart
	else
	    /etc/init.d/ssh restart
	fi
    ;;
    upgrade|deconfigure)
    ;;

    failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
